services:
  app:
    image: node:22.14.0-alpine
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: npm run start:dev
    ports:
      - 8080:8080
    networks:
      - back
    restart: always
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16.8-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=garagee-app
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - back
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    restart: always

networks:
  back:

volumes:
  db_data:
